import { createCipheriv, createECDH, createHmac, createPrivateKey, generateKeyPairSync, randomBytes, sign } from "crypto";

// Web Push, done with Node's own crypto rather than a library: message
// encryption (RFC 8291, the aes128gcm content coding of RFC 8188) and the
// VAPID signature that identifies this server to the push service (RFC
// 8292). Pure, no database, so it's tested against the RFC's own example.
//
// A browser's push service (Apple's, Google's, Mozilla's) only ever carries
// the encrypted record: the key that opens it lives in the browser, and the
// VAPID key that signs it was generated by this server. No account or API
// key with any of them is involved.

export type PushSubscriptionKeys = {
  endpoint: string;
  /** The browser's P-256 public key, base64url, 65 bytes uncompressed. */
  p256dh: string;
  /** The browser's 16-byte auth secret, base64url. */
  auth: string;
};

export type VapidKeys = {
  /** base64url, 65-byte uncompressed P-256 point: what browsers subscribe with. */
  publicKey: string;
  /** base64url, the 32-byte private scalar. */
  privateKey: string;
};

/** Push services browsers actually use. A subscription's endpoint is where
 * this server POSTs, so it's held to this list rather than trusting
 * whatever URL a signed-in browser hands over (which could otherwise point
 * the server at something on the local network). */
const PUSH_SERVICE_HOSTS = [
  "fcm.googleapis.com", // Chrome, Edge on Android, Brave, Opera, Samsung Internet
  "android.googleapis.com",
  "push.services.mozilla.com", // Firefox (updates.push.services.mozilla.com)
  "push.apple.com", // Safari on macOS and iOS (web.push.apple.com)
  "notify.windows.com", // Edge on Windows (wns2-….notify.windows.com)
];

export function isAllowedPushEndpoint(endpoint: string): boolean {
  let url: URL;
  try {
    url = new URL(endpoint);
  } catch {
    return false;
  }
  if (url.protocol !== "https:" || url.port !== "") return false;
  const host = url.hostname.toLowerCase();
  return PUSH_SERVICE_HOSTS.some((allowed) => host === allowed || host.endsWith(`.${allowed}`));
}

/** Record size advertised in the header. One record holds any payload this
 * server sends (the push services cap payloads at 4 KB anyway). */
const RECORD_SIZE = 4096;

function b64url(buffer: Buffer): string {
  return buffer.toString("base64url");
}

function hmac(key: Buffer, data: Buffer): Buffer {
  return createHmac("sha256", key).update(data).digest();
}

/** A fresh VAPID key pair. */
export function generateVapidKeys(): VapidKeys {
  const { publicKey, privateKey } = generateKeyPairSync("ec", { namedCurve: "prime256v1" });
  const jwk = publicKey.export({ format: "jwk" });
  const point = Buffer.concat([Buffer.from([0x04]), Buffer.from(jwk.x!, "base64url"), Buffer.from(jwk.y!, "base64url")]);
  const d = privateKey.export({ format: "jwk" }).d!;
  return { publicKey: b64url(point), privateKey: d };
}

/**
 * Encrypts one push message for one browser (RFC 8291 §3). `salt` and
 * `senderPrivateKey` are only ever passed by tests, to reproduce the RFC's
 * worked example; real sends get fresh random ones every time.
 */
export function encryptPayload(
  subscription: Pick<PushSubscriptionKeys, "p256dh" | "auth">,
  plaintext: Buffer,
  fixed?: { salt: Buffer; senderPrivateKey: Buffer },
): Buffer {
  const uaPublic = Buffer.from(subscription.p256dh, "base64url");
  const authSecret = Buffer.from(subscription.auth, "base64url");
  if (uaPublic.length !== 65 || uaPublic[0] !== 0x04) throw new Error("Invalid p256dh key");
  if (authSecret.length !== 16) throw new Error("Invalid auth secret");

  const sender = createECDH("prime256v1");
  if (fixed) sender.setPrivateKey(fixed.senderPrivateKey);
  else sender.generateKeys();
  const asPublic = sender.getPublicKey();
  const ecdhSecret = sender.computeSecret(uaPublic);

  // IKM = HKDF(auth_secret, ecdh_secret, "WebPush: info" || 0x00 || ua_public || as_public, 32)
  const keyInfo = Buffer.concat([Buffer.from("WebPush: info\0"), uaPublic, asPublic]);
  const ikm = hmac(hmac(authSecret, ecdhSecret), Buffer.concat([keyInfo, Buffer.from([0x01])]));

  // RFC 8188: the content-encryption key and nonce, from a random salt.
  const salt = fixed?.salt ?? randomBytes(16);
  const prk = hmac(salt, ikm);
  const cek = hmac(prk, Buffer.from("Content-Encoding: aes128gcm\0\x01")).subarray(0, 16);
  const nonce = hmac(prk, Buffer.from("Content-Encoding: nonce\0\x01")).subarray(0, 12);

  // A single, final record: the payload then the 0x02 last-record delimiter.
  const cipher = createCipheriv("aes-128-gcm", cek, nonce);
  const record = Buffer.concat([cipher.update(Buffer.concat([plaintext, Buffer.from([0x02])])), cipher.final(), cipher.getAuthTag()]);

  const header = Buffer.alloc(16 + 4 + 1);
  salt.copy(header, 0);
  header.writeUInt32BE(RECORD_SIZE, 16);
  header.writeUInt8(asPublic.length, 20);
  return Buffer.concat([header, asPublic, record]);
}

/** The `Authorization: vapid t=…, k=…` header for one push service (RFC
 * 8292). The token's audience is the push service's origin; `subject` is a
 * contact (an https URL or mailto:) some services insist on. */
export function vapidAuthorization(endpoint: string, keys: VapidKeys, subject: string, now = Date.now()): string {
  const header = b64url(Buffer.from(JSON.stringify({ typ: "JWT", alg: "ES256" })));
  const claims = b64url(
    Buffer.from(
      JSON.stringify({
        aud: new URL(endpoint).origin,
        // 12 hours: under the 24-hour maximum the services accept.
        exp: Math.floor(now / 1000) + 12 * 60 * 60,
        sub: subject,
      }),
    ),
  );
  const point = Buffer.from(keys.publicKey, "base64url");
  const key = createPrivateKey({
    format: "jwk",
    key: {
      kty: "EC",
      crv: "P-256",
      x: b64url(point.subarray(1, 33)),
      y: b64url(point.subarray(33, 65)),
      d: keys.privateKey,
    },
  });
  const signature = sign("sha256", Buffer.from(`${header}.${claims}`), { key, dsaEncoding: "ieee-p1363" });
  return `vapid t=${header}.${claims}.${b64url(signature)}, k=${keys.publicKey}`;
}

export type PushSendResult =
  /** Delivered to the push service. */
  | { status: "sent" }
  /** The browser unsubscribed or the subscription expired: forget it. */
  | { status: "gone" }
  /** Worth trying again next time (rate limited, service trouble, offline). */
  | { status: "failed"; detail: string };

/** Sends one encrypted message to one browser's push service. */
export async function sendWebPush(
  subscription: PushSubscriptionKeys,
  payload: object,
  keys: VapidKeys,
  subject: string,
  options: { ttlSeconds?: number; urgency?: "very-low" | "low" | "normal" | "high"; topic?: string } = {},
): Promise<PushSendResult> {
  let body: Buffer;
  try {
    body = encryptPayload(subscription, Buffer.from(JSON.stringify(payload)));
  } catch {
    // Keys the browser handed over that aren't valid keys: nothing will
    // ever decrypt for this subscription.
    return { status: "gone" };
  }

  try {
    const res = await fetch(subscription.endpoint, {
      method: "POST",
      headers: {
        Authorization: vapidAuthorization(subscription.endpoint, keys, subject),
        "Content-Encoding": "aes128gcm",
        "Content-Type": "application/octet-stream",
        TTL: String(options.ttlSeconds ?? 24 * 60 * 60),
        Urgency: options.urgency ?? "normal",
        // A later push with the same topic replaces an undelivered one.
        ...(options.topic ? { Topic: options.topic } : {}),
      },
      body: new Uint8Array(body),
      signal: AbortSignal.timeout(10_000),
    });
    if (res.status === 404 || res.status === 410) return { status: "gone" };
    if (!res.ok) return { status: "failed", detail: `${res.status} ${await res.text().catch(() => "")}`.trim() };
    return { status: "sent" };
  } catch (err) {
    return { status: "failed", detail: err instanceof Error ? err.message : String(err) };
  }
}
