// Generated by scripts/i18n-index.py: every namespace of every language,
// imported statically. Add a language or a namespace there and re-run it
// rather than editing this by hand.

import en_common from "./en/common.json";
import en_nav from "./en/nav.json";
import en_auth from "./en/auth.json";
import en_discover from "./en/discover.json";
import en_title from "./en/title.json";
import en_requests from "./en/requests.json";
import en_settings from "./en/settings.json";
import en_integrations from "./en/integrations.json";
import en_help from "./en/help.json";
import en_server from "./en/server.json";
import en_notify from "./en/notify.json";
import en_admin from "./en/admin.json";
import en_library from "./en/library.json";
import es_common from "./es/common.json";
import es_nav from "./es/nav.json";
import es_auth from "./es/auth.json";
import es_discover from "./es/discover.json";
import es_title from "./es/title.json";
import es_requests from "./es/requests.json";
import es_settings from "./es/settings.json";
import es_integrations from "./es/integrations.json";
import es_help from "./es/help.json";
import es_server from "./es/server.json";
import es_notify from "./es/notify.json";
import es_admin from "./es/admin.json";
import es_library from "./es/library.json";
import fr_common from "./fr/common.json";
import fr_nav from "./fr/nav.json";
import fr_auth from "./fr/auth.json";
import fr_discover from "./fr/discover.json";
import fr_title from "./fr/title.json";
import fr_requests from "./fr/requests.json";
import fr_settings from "./fr/settings.json";
import fr_integrations from "./fr/integrations.json";
import fr_help from "./fr/help.json";
import fr_server from "./fr/server.json";
import fr_notify from "./fr/notify.json";
import fr_admin from "./fr/admin.json";
import fr_library from "./fr/library.json";
import de_common from "./de/common.json";
import de_nav from "./de/nav.json";
import de_auth from "./de/auth.json";
import de_discover from "./de/discover.json";
import de_title from "./de/title.json";
import de_requests from "./de/requests.json";
import de_settings from "./de/settings.json";
import de_integrations from "./de/integrations.json";
import de_help from "./de/help.json";
import de_server from "./de/server.json";
import de_notify from "./de/notify.json";
import de_admin from "./de/admin.json";
import de_library from "./de/library.json";
import ptBR_common from "./pt-BR/common.json";
import ptBR_nav from "./pt-BR/nav.json";
import ptBR_auth from "./pt-BR/auth.json";
import ptBR_discover from "./pt-BR/discover.json";
import ptBR_title from "./pt-BR/title.json";
import ptBR_requests from "./pt-BR/requests.json";
import ptBR_settings from "./pt-BR/settings.json";
import ptBR_integrations from "./pt-BR/integrations.json";
import ptBR_help from "./pt-BR/help.json";
import ptBR_server from "./pt-BR/server.json";
import ptBR_notify from "./pt-BR/notify.json";
import ptBR_admin from "./pt-BR/admin.json";
import ptBR_library from "./pt-BR/library.json";

export const NAMESPACES = ["common", "nav", "auth", "discover", "title", "requests", "settings", "integrations", "help", "server", "notify", "admin", "library"] as const;

/** English, the source: its keys are the only valid ones. */
export const english = {
  common: en_common,
  nav: en_nav,
  auth: en_auth,
  discover: en_discover,
  title: en_title,
  requests: en_requests,
  settings: en_settings,
  integrations: en_integrations,
  help: en_help,
  server: en_server,
  notify: en_notify,
  admin: en_admin,
  library: en_library,
};

/** One language's messages: any of English's keys, each a string. */
export type Catalog = { [Namespace in keyof typeof english]: Partial<Record<keyof (typeof english)[Namespace], string>> };

export const catalogs = {
  en: {
    common: en_common,
    nav: en_nav,
    auth: en_auth,
    discover: en_discover,
    title: en_title,
    requests: en_requests,
    settings: en_settings,
    integrations: en_integrations,
    help: en_help,
    server: en_server,
    notify: en_notify,
    admin: en_admin,
    library: en_library,
  },
  es: {
    common: es_common,
    nav: es_nav,
    auth: es_auth,
    discover: es_discover,
    title: es_title,
    requests: es_requests,
    settings: es_settings,
    integrations: es_integrations,
    help: es_help,
    server: es_server,
    notify: es_notify,
    admin: es_admin,
    library: es_library,
  },
  fr: {
    common: fr_common,
    nav: fr_nav,
    auth: fr_auth,
    discover: fr_discover,
    title: fr_title,
    requests: fr_requests,
    settings: fr_settings,
    integrations: fr_integrations,
    help: fr_help,
    server: fr_server,
    notify: fr_notify,
    admin: fr_admin,
    library: fr_library,
  },
  de: {
    common: de_common,
    nav: de_nav,
    auth: de_auth,
    discover: de_discover,
    title: de_title,
    requests: de_requests,
    settings: de_settings,
    integrations: de_integrations,
    help: de_help,
    server: de_server,
    notify: de_notify,
    admin: de_admin,
    library: de_library,
  },
  "pt-BR": {
    common: ptBR_common,
    nav: ptBR_nav,
    auth: ptBR_auth,
    discover: ptBR_discover,
    title: ptBR_title,
    requests: ptBR_requests,
    settings: ptBR_settings,
    integrations: ptBR_integrations,
    help: ptBR_help,
    server: ptBR_server,
    notify: ptBR_notify,
    admin: ptBR_admin,
    library: ptBR_library,
  },
} satisfies Record<string, Catalog>;
