#!/usr/bin/env python3
"""Writes lib/i18n/messages/index.ts: every namespace of every language,
imported statically. Run it after adding a language or a namespace:

    python3 scripts/i18n-index.py

It also creates any missing namespace file (as {}) so each language has
the same set. See docs/translating.md.
"""
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "lib", "i18n", "messages")

# Keep in step with LOCALES in lib/i18n/locales.ts (English first).
LOCALES = ["en", "es", "fr", "de", "pt-BR"]
NAMESPACES = [
    "common",
    "nav",
    "auth",
    "discover",
    "title",
    "requests",
    "settings",
    "integrations",
    "help",
    "server",
    "notify",
    "admin",
]


def ident(locale, namespace):
    return locale.replace("-", "") + "_" + namespace


def main():
    for locale in LOCALES:
        os.makedirs(os.path.join(ROOT, locale), exist_ok=True)
        for namespace in NAMESPACES:
            path = os.path.join(ROOT, locale, namespace + ".json")
            if not os.path.exists(path):
                with open(path, "w") as file:
                    file.write("{}\n")

    lines = [
        "// Generated by scripts/i18n-index.py: every namespace of every language,",
        "// imported statically. Add a language or a namespace there and re-run it",
        "// rather than editing this by hand.",
        "",
    ]
    for locale in LOCALES:
        for namespace in NAMESPACES:
            lines.append(f'import {ident(locale, namespace)} from "./{locale}/{namespace}.json";')
    lines += [
        "",
        "export const NAMESPACES = [" + ", ".join(f'"{n}"' for n in NAMESPACES) + "] as const;",
        "",
        "/** English, the source: its keys are the only valid ones. */",
        "export const english = {",
    ]
    lines += [f"  {n}: {ident('en', n)}," for n in NAMESPACES]
    lines += [
        "};",
        "",
        "/** One language's messages: any of English's keys, each a string. */",
        "export type Catalog = { [Namespace in keyof typeof english]: Partial<Record<keyof (typeof english)[Namespace], string>> };",
        "",
        "export const catalogs = {",
    ]
    for locale in LOCALES:
        key = f'"{locale}"' if "-" in locale else locale
        lines.append(f"  {key}: {{")
        lines += [f"    {n}: {ident(locale, n)}," for n in NAMESPACES]
        lines.append("  },")
    lines.append("} satisfies Record<string, Catalog>;")
    with open(os.path.join(ROOT, "index.ts"), "w") as file:
        file.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
